apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kodabank.fullname" . }}-postgres
  labels:
    {{- include "kodabank.labels" . | nindent 4 }}
type: Opaque
stringData:
  eventstore-password: {{ .Values.postgres.eventstore.password | quote }}
  readmodel-password: {{ .Values.postgres.readmodel.password | quote }}
  keycloak-password: {{ .Values.postgres.keycloak.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kodabank.fullname" . }}-keycloak
  labels:
    {{- include "kodabank.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.keycloak.adminPassword | quote }}
  client-secret: {{ .Values.keycloak.clientSecret | quote }}
