/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateBankRouteImport } from './routes/create-bank'
import { Route as TenantRouteRouteImport } from './routes/$tenant/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantTransfersRouteImport } from './routes/$tenant/transfers'
import { Route as TenantLoginRouteImport } from './routes/$tenant/login'
import { Route as TenantJoinRouteImport } from './routes/$tenant/join'
import { Route as TenantDashboardRouteImport } from './routes/$tenant/dashboard'
import { Route as TenantCardsRouteImport } from './routes/$tenant/cards'
import { Route as TenantAdminRouteImport } from './routes/$tenant/admin'
import { Route as TenantPaymentsIndexRouteImport } from './routes/$tenant/payments/index'
import { Route as TenantAccountsIndexRouteImport } from './routes/$tenant/accounts/index'
import { Route as TenantPaymentsNewRouteImport } from './routes/$tenant/payments/new'
import { Route as TenantCheckoutOrderIdRouteImport } from './routes/$tenant/checkout.$orderId'
import { Route as TenantAccountsIdRouteImport } from './routes/$tenant/accounts/$id'

const CreateBankRoute = CreateBankRouteImport.update({
  id: '/create-bank',
  path: '/create-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRouteRoute = TenantRouteRouteImport.update({
  id: '/$tenant',
  path: '/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantTransfersRoute = TenantTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantLoginRoute = TenantLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantJoinRoute = TenantJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantDashboardRoute = TenantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantCardsRoute = TenantCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantAdminRoute = TenantAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantPaymentsIndexRoute = TenantPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantAccountsIndexRoute = TenantAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantPaymentsNewRoute = TenantPaymentsNewRouteImport.update({
  id: '/payments/new',
  path: '/payments/new',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantCheckoutOrderIdRoute = TenantCheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantAccountsIdRoute = TenantAccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => TenantRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteRouteWithChildren
  '/create-bank': typeof CreateBankRoute
  '/$tenant/admin': typeof TenantAdminRoute
  '/$tenant/cards': typeof TenantCardsRoute
  '/$tenant/dashboard': typeof TenantDashboardRoute
  '/$tenant/join': typeof TenantJoinRoute
  '/$tenant/login': typeof TenantLoginRoute
  '/$tenant/transfers': typeof TenantTransfersRoute
  '/$tenant/accounts/$id': typeof TenantAccountsIdRoute
  '/$tenant/checkout/$orderId': typeof TenantCheckoutOrderIdRoute
  '/$tenant/payments/new': typeof TenantPaymentsNewRoute
  '/$tenant/accounts/': typeof TenantAccountsIndexRoute
  '/$tenant/payments/': typeof TenantPaymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteRouteWithChildren
  '/create-bank': typeof CreateBankRoute
  '/$tenant/admin': typeof TenantAdminRoute
  '/$tenant/cards': typeof TenantCardsRoute
  '/$tenant/dashboard': typeof TenantDashboardRoute
  '/$tenant/join': typeof TenantJoinRoute
  '/$tenant/login': typeof TenantLoginRoute
  '/$tenant/transfers': typeof TenantTransfersRoute
  '/$tenant/accounts/$id': typeof TenantAccountsIdRoute
  '/$tenant/checkout/$orderId': typeof TenantCheckoutOrderIdRoute
  '/$tenant/payments/new': typeof TenantPaymentsNewRoute
  '/$tenant/accounts': typeof TenantAccountsIndexRoute
  '/$tenant/payments': typeof TenantPaymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteRouteWithChildren
  '/create-bank': typeof CreateBankRoute
  '/$tenant/admin': typeof TenantAdminRoute
  '/$tenant/cards': typeof TenantCardsRoute
  '/$tenant/dashboard': typeof TenantDashboardRoute
  '/$tenant/join': typeof TenantJoinRoute
  '/$tenant/login': typeof TenantLoginRoute
  '/$tenant/transfers': typeof TenantTransfersRoute
  '/$tenant/accounts/$id': typeof TenantAccountsIdRoute
  '/$tenant/checkout/$orderId': typeof TenantCheckoutOrderIdRoute
  '/$tenant/payments/new': typeof TenantPaymentsNewRoute
  '/$tenant/accounts/': typeof TenantAccountsIndexRoute
  '/$tenant/payments/': typeof TenantPaymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenant'
    | '/create-bank'
    | '/$tenant/admin'
    | '/$tenant/cards'
    | '/$tenant/dashboard'
    | '/$tenant/join'
    | '/$tenant/login'
    | '/$tenant/transfers'
    | '/$tenant/accounts/$id'
    | '/$tenant/checkout/$orderId'
    | '/$tenant/payments/new'
    | '/$tenant/accounts/'
    | '/$tenant/payments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$tenant'
    | '/create-bank'
    | '/$tenant/admin'
    | '/$tenant/cards'
    | '/$tenant/dashboard'
    | '/$tenant/join'
    | '/$tenant/login'
    | '/$tenant/transfers'
    | '/$tenant/accounts/$id'
    | '/$tenant/checkout/$orderId'
    | '/$tenant/payments/new'
    | '/$tenant/accounts'
    | '/$tenant/payments'
  id:
    | '__root__'
    | '/'
    | '/$tenant'
    | '/create-bank'
    | '/$tenant/admin'
    | '/$tenant/cards'
    | '/$tenant/dashboard'
    | '/$tenant/join'
    | '/$tenant/login'
    | '/$tenant/transfers'
    | '/$tenant/accounts/$id'
    | '/$tenant/checkout/$orderId'
    | '/$tenant/payments/new'
    | '/$tenant/accounts/'
    | '/$tenant/payments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantRouteRoute: typeof TenantRouteRouteWithChildren
  CreateBankRoute: typeof CreateBankRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create-bank': {
      id: '/create-bank'
      path: '/create-bank'
      fullPath: '/create-bank'
      preLoaderRoute: typeof CreateBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant': {
      id: '/$tenant'
      path: '/$tenant'
      fullPath: '/$tenant'
      preLoaderRoute: typeof TenantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/transfers': {
      id: '/$tenant/transfers'
      path: '/transfers'
      fullPath: '/$tenant/transfers'
      preLoaderRoute: typeof TenantTransfersRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/login': {
      id: '/$tenant/login'
      path: '/login'
      fullPath: '/$tenant/login'
      preLoaderRoute: typeof TenantLoginRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/join': {
      id: '/$tenant/join'
      path: '/join'
      fullPath: '/$tenant/join'
      preLoaderRoute: typeof TenantJoinRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/dashboard': {
      id: '/$tenant/dashboard'
      path: '/dashboard'
      fullPath: '/$tenant/dashboard'
      preLoaderRoute: typeof TenantDashboardRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/cards': {
      id: '/$tenant/cards'
      path: '/cards'
      fullPath: '/$tenant/cards'
      preLoaderRoute: typeof TenantCardsRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/admin': {
      id: '/$tenant/admin'
      path: '/admin'
      fullPath: '/$tenant/admin'
      preLoaderRoute: typeof TenantAdminRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/payments/': {
      id: '/$tenant/payments/'
      path: '/payments'
      fullPath: '/$tenant/payments/'
      preLoaderRoute: typeof TenantPaymentsIndexRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/accounts/': {
      id: '/$tenant/accounts/'
      path: '/accounts'
      fullPath: '/$tenant/accounts/'
      preLoaderRoute: typeof TenantAccountsIndexRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/payments/new': {
      id: '/$tenant/payments/new'
      path: '/payments/new'
      fullPath: '/$tenant/payments/new'
      preLoaderRoute: typeof TenantPaymentsNewRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/checkout/$orderId': {
      id: '/$tenant/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/$tenant/checkout/$orderId'
      preLoaderRoute: typeof TenantCheckoutOrderIdRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/accounts/$id': {
      id: '/$tenant/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/$tenant/accounts/$id'
      preLoaderRoute: typeof TenantAccountsIdRouteImport
      parentRoute: typeof TenantRouteRoute
    }
  }
}

interface TenantRouteRouteChildren {
  TenantAdminRoute: typeof TenantAdminRoute
  TenantCardsRoute: typeof TenantCardsRoute
  TenantDashboardRoute: typeof TenantDashboardRoute
  TenantJoinRoute: typeof TenantJoinRoute
  TenantLoginRoute: typeof TenantLoginRoute
  TenantTransfersRoute: typeof TenantTransfersRoute
  TenantAccountsIdRoute: typeof TenantAccountsIdRoute
  TenantCheckoutOrderIdRoute: typeof TenantCheckoutOrderIdRoute
  TenantPaymentsNewRoute: typeof TenantPaymentsNewRoute
  TenantAccountsIndexRoute: typeof TenantAccountsIndexRoute
  TenantPaymentsIndexRoute: typeof TenantPaymentsIndexRoute
}

const TenantRouteRouteChildren: TenantRouteRouteChildren = {
  TenantAdminRoute: TenantAdminRoute,
  TenantCardsRoute: TenantCardsRoute,
  TenantDashboardRoute: TenantDashboardRoute,
  TenantJoinRoute: TenantJoinRoute,
  TenantLoginRoute: TenantLoginRoute,
  TenantTransfersRoute: TenantTransfersRoute,
  TenantAccountsIdRoute: TenantAccountsIdRoute,
  TenantCheckoutOrderIdRoute: TenantCheckoutOrderIdRoute,
  TenantPaymentsNewRoute: TenantPaymentsNewRoute,
  TenantAccountsIndexRoute: TenantAccountsIndexRoute,
  TenantPaymentsIndexRoute: TenantPaymentsIndexRoute,
}

const TenantRouteRouteWithChildren = TenantRouteRoute._addFileChildren(
  TenantRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantRouteRoute: TenantRouteRouteWithChildren,
  CreateBankRoute: CreateBankRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
