server:
  port: ${SERVER_PORT:8087}

kodastore:
  url: ${KODASTORE_URL:http://localhost:8080}

spring:
  application:
    name: kodabank-clearing
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/kodabank_readmodel}
    username: ${SPRING_DATASOURCE_USERNAME:kodabank}
    password: ${SPRING_DATASOURCE_PASSWORD:kodabank}
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
